# Generated by Django 3.0.8 on 2020-08-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex_variants", "0003_auto_20200804_2134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationubs",
            name="category",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "A"), (2, "B"), (3, "C"), (4, "D")],
                default=None,
                null=True,
            ),
        ),
    ]
