# Generated by Django 3.0.8 on 2020-08-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex_variants", "0005_auto_20200804_2135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dcodex_variants.LocationBase",
            ),
        ),
    ]
