# Generated by Django 3.0.8 on 2020-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex_variants", "0006_auto_20200804_2137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="locations",
            field=models.ManyToManyField(to="dcodex_variants.LocationBase"),
        ),
    ]
