# Generated by Django 3.0.8 on 2020-08-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_variants', '0011_auto_20200815_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contra',
            name='family_witness',
        ),
    ]
