# Generated by Django 3.2.8 on 2023-07-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_variants', '0013_extantverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='siglumwitness',
            name='origin_date_earliest',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='siglumwitness',
            name='origin_date_latest',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
