# Generated by Django 3.2.8 on 2023-07-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_variants', '0014_auto_20230721_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='familywitness',
            name='origin_date_earliest',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='familywitness',
            name='origin_date_latest',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
