# Generated by Django 3.2.25 on 2025-03-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_variants', '0015_auto_20230721_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationbase',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='reading',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
    ]
